import Head from "next/head"
import Link from "next/link"
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillGithub, AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import Profile from "../public/LinkedIn_Profile.png";
import axios from 'axios';
import { useState, useEffect} from "react";
import factApi from "./api/getFact";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [fact, setFact] = useState();
 
  useEffect(() => {
    function getData() {
       factApi.get('v1/facts?limit=1').then(function(response) {
        setFact(response.data[0].fact);
      }).catch((error) => {
        console.log(error);
      });
    }
    
    getData();
  }, []);
  
  if (fact == null ) {return null}

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Harris Crews Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="../styles/tailwind.output.css"/>
      </Head>

      <main className="bg-[#FAF7F0] dark:bg-[#082032]">
        <section className="min-h-screen">
          <nav className=" py-10 px-5 mb-2 flex justify-between bg-[#CDFCF6] dark:bg-[#334756] shadow-lg lg:px-10">
            <h1 className="text-black dark:text-white text-xl font-burtons lg:text-3xl">My Simple Website</h1>
            <ul className="flex items-center lg:gap-20">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-xl lg:text-4xl dark:text-white"/></li>
              <li><Link href="./resume"><a  className="bg-gradient-to-t  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 lg:text-2xl dark:bg-gradient-to-t dark:from-[#f25637] dark:to-[#fd2a00]">Resume</a></Link></li>
            </ul>
          </nav>
          <div className="text-center py-5 mx-5">
            <h2 className="text-5xl py-2 text-[#98A8F8] dark:text-[#FF4C29] font-medium">Harris Crews</h2>
            <h3 className="text-2xl py-2 text-black dark:text-white">Software Developer</h3>
            {/* <p className="dark:text-white">{fact}</p> */}
            <div className="relative rounded-full mx-auto mt-5 w-72 h-72 border-2 border-gray-400 shadow-xl lg:w-60 lg:h-60">
              <Image src={Profile} className="rounded-full" layout="fill" objectFit="cover"/>
            </div>
            <p className="my-5  bg-gray-200 dark:bg-[#334756] dark:text-white rounded-md shadow-md text-md py-5 leading-7 text-gray-800 lg:mx-80"> Hello, my name is Harris Crews! I’m a software developer, currently working at Amdocs in Alpharetta, GA. I am hard-working and dedicated to my assignments. I love working within a team setting that encourages teamwork and communication. I find that time flys by when I am working on a challenging problem and love the feeling accomplishment when it's solved. Every day I strive to improve myself by learning something new or brushing up on an already-known topic, if the subject is related to computer science, you have my full attention. </p>
            <div className="flex justify-center text-4xl gap-10 text-gray-600 ">
              <a href="https://github.com/whcrews1998" target="blank"> <AiFillGithub className=" cursor-pointer lg:text-6xl lg:mr-20 dark:text-white"/> </a>
             <a href="https://linkedin.com/in/harris-crews-587813231" target="blank"><AiFillLinkedin className=" cursor-pointer lg:text-6xl dark:text-white"/></a> 
            </div>
          </div>
        </section>

        <section>
          <div>

          </div>
        </section>
        
      </main>

    </div>
  )
}


