import Head from "next/head"
import Link from "next/link"
import {BsFillMoonStarsFill} from "react-icons/bs"
import {AiFillGithub, AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import Profile from "../public/LinkedIn_Profile.png";
import axios from 'axios';
import { useState, useEffect} from "react";
import factApi from "./api/getFact";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [fact, setFact] = useState();
 
  useEffect(() => {
    function getData() {
       factApi.get('v1/facts?limit=1').then(function(response) {
        setFact(response.data[0].fact);
      }).catch((error) => {
        console.log(error);
      });
    }
    
    getData();
  }, []);
  
  if (fact == null ) {return null}

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Harris Crews Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="../styles/tailwind.output.css"/>
      </Head>

      <main className="bg-[#FAF7F0] dark:bg-[#082032]">
        <section className="min-h-screen">
          <nav className=" py-10 px-5 mb-2 flex justify-between bg-[#CDFCF6] dark:bg-[#334756] shadow-lg lg:px-10">
            <h1 className="text-black dark:text-white text-xl font-burtons lg:text-3xl">Crews Inc.</h1>
            <ul className="flex items-center lg:gap-20">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-xl lg:text-4xl dark:text-white"/></li>
              <li><Link href="./resume"><a  className="bg-gradient-to-t  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 lg:text-2xl dark:bg-gradient-to-t dark:from-[#f25637] dark:to-[#fd2a00]">Resume</a></Link></li>
            </ul>
          </nav>
          <div className="text-center py-5 mx-5">
            <h2 className="text-5xl py-2 text-[#98A8F8] dark:text-[#FF4C29] font-medium">Harris Crews</h2>
            <h3 className="text-2xl py-2 text-black dark:text-white">Software Developer</h3>
            {/* <p className="dark:text-white">{fact}</p> */}
            <div className="relative rounded-full mx-auto mt-5 w-72 h-72 border-2 border-gray-400 shadow-xl lg:w-60 lg:h-60">
              <Image src={Profile} className="rounded-full" layout="fill" objectFit="cover"/>
            </div>
            <p className="my-5  bg-gray-200 dark:bg-[#334756] dark:text-white rounded-md shadow-md text-md py-5 leading-7 text-gray-800 lg:mx-80"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <div className="flex justify-center text-4xl gap-10 text-gray-600 ">
              <a href="https://github.com/whcrews1998" target="blank"> <AiFillGithub className=" cursor-pointer lg:text-6xl lg:mr-20 dark:text-white"/> </a>
             <a href="https://linkedin.com/in/harris-crews-587813231" target="blank"><AiFillLinkedin className=" cursor-pointer lg:text-6xl dark:text-white"/></a> 
            </div>
          </div>
        </section>

        <section>
          <div>

          </div>
        </section>
        
      </main>

    </div>
  )
}


